# Generated by Django 3.2.13 on 2022-05-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=70)),
                ('salary', models.CharField(max_length=10, null=True)),
                ('job_type', models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time')], max_length=10)),
                ('category', models.CharField(choices=[('Web Developers', ''), ('Mobile Developers', ''), ('UI/UX Designer', ''), ('Machine Learning Engineer', ''), ('Data Scientist', ''), ('Game Developer', ''), ('Security Engineer', '')], max_length=10)),
                ('description', models.TextField()),
                ('app_email', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
