# Generated by Django 3.2.13 on 2022-06-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobblog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('webdev', 'Web Developers'), ('mobiledev', 'Mobile Developers'), ('ui_ux', 'UI/UX Designer'), ('mleng', 'Machine Learning Engineer'), ('ds', 'Data Scientist'), ('gamedev', 'Game Developer'), ('isse', 'Security Engineer')], max_length=50),
        ),
    ]
