# Generated by Django 3.2.13 on 2022-06-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobblog', '0005_rename_app_email_post_application_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='application_email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='company',
        ),
    ]
