# Generated by Django 3.2.13 on 2022-06-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobblog', '0006_auto_20220601_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hours',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
