# Generated by Django 3.2.13 on 2022-06-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobblog', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'full-time'), ('Part-time', 'part-time')], max_length=20),
        ),
    ]
