# Generated by Django 3.2.13 on 2022-06-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobblog', '0009_alter_post_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=20),
        ),
    ]
