# Generated by Django 3.2.13 on 2022-06-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobblog', '0010_alter_post_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='logo'),
        ),
    ]
