# Generated by Django 3.2.13 on 2022-06-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobblog', '0012_alter_post_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
