# Generated by Django 3.2.13 on 2022-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobblog', '0016_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hours',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
